enyo.depends(
	"css/MyLastFM.css",
	"$enyo-lib/systemui/",
	"source/LastFM/",
	"source/Scrim.js",
	"source/Preferences.js",
	"source/Map.js",
	"source/Detail.js",
	"source/Event.js",
	"source/ArtistEvents.js",
	"source/ArtistSearch.js",
	"source/GeoEventsSearch.js",
	"source/App.js"
);